<link rel="stylesheet" href="/_resources/css/bootstrap.min.css">
<link rel="stylesheet" href="/_resources/css/bootstrap-grid.min.css">
<link rel="stylesheet" href="/_resources/css/bootstrap-reboot.min.css">

<!-- Gallena University CSS -->
<link rel="stylesheet" href="/_resources/css/styles.css">
<link rel="stylesheet" href="/_resources/css/print.css">
<link href="/_resources/css/totopstyle.css" rel="stylesheet">
<link rel="stylesheet" href="/_resources/css/slick.css"/>
<link rel="stylesheet" href="/_resources/css/slick-theme.css"/>
<link rel="stylesheet" href="/_resources/css/slick-lightbox.css">
<link rel="stylesheet" href="/_resources/css/lightbox.css">
<link rel="stylesheet" href="/_resources/css/animate.css">

<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
<![endif]-->

<!-- Font Awescome CDN -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">

<!-- Video.js CDN -->
<link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
<!-- Sea Theme -->
<link href="https://unpkg.com/@videojs/themes@1/dist/sea/index.css" rel="stylesheet">

<link rel="stylesheet" href="/_resources/css/oustyles.css">